service: my-service

provider:
  name: google
  stage: dev
  runtime: nodejs10
  timeout: 5s
  memorySize: 256
  region: us-central1
  project: telegrambot-255720
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: C:\Users\STEM 10\PhpstormProjects\telegraf-homework\bot_credentials.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-webpack
custom:
  webpack:
    webpackConfig: './webpack.build.config.js'   # Name of webpack configuration file
    #includeModules: true   # Node modules configuration for packaging
    includeModules:
      packagePath: './package.json'
    packager: 'yarn'   # Packager that will be used to package your external modules


# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  tg_bot:
    handler: tg_bot
    events: # All events associated with this function
      - http: path
  vk_bot:
    handler: vk_bot
    events: # All events associated with this function
      - http: path
  commands:
    handler: commands
    events: # All events associated with this function
      - http: path
